replicaCount: 1
namespace: feature-platform

image:
  repository: asia-southeast1-docker.pkg.dev/PROJECT_ID/coinbase-mlops/coinbase-feature-platform
  tag: dev
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

store:
  historyLimit: 200
  online: redis
  offline: postgres
  dataVersion: local-dev
  drift:
    returnDeltaThreshold: "0.005"
    volumeDeltaRatioThreshold: "0.25"
  redis:
    enabled: true
    url: redis://feature-platform-redis:6379/0
    image: redis:7.4-alpine
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  postgres:
    enabled: true
    dsn: postgresql://feature_user:feature_password@feature-platform-postgres:5432/feature_store
    image: postgres:16-alpine
    database: feature_store
    username: feature_user
    password: feature_password
    storageSize: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

podSecurityContext: {}

containerSecurityContext: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
