sonar.projectKey=Coinbase-Streaming
sonar.projectName=Coinbase Streaming
sonar.projectVersion=0.1.0

sonar.sources=coinbase_kafka_producer,go_kafka_consumer,kafka_spark_processor,mlops,scripts,charts,infra
sonar.exclusions=**/__pycache__/**,**/.venv*/**,artifacts/**,data/**,mlruns/**,notebooks/**,grafana/**,monitoring/**,jenkins_home/**,charts/**/templates/**,**/*.joblib

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
