apiVersion: v1
kind: Namespace
metadata:
  name: crypto-pipeline
  labels:
    name: crypto-pipeline
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: crypto-monitoring
  labels:
    name: crypto-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: crypto-mlops
  labels:
    name: crypto-mlops
