replicaCount: 1

image:
  repository: asia-southeast1-docker.pkg.dev/PROJECT_ID/coinbase-mlops/coinbase-bento-price-predictor
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /

model:
  fileName: coinbase_ml_model.joblib

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
