apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feature-platform.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "feature-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "feature-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "feature-platform.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "feature-platform.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: FEATURE_HISTORY_LIMIT
              value: {{ .Values.store.historyLimit | quote }}
            - name: FEATURE_ONLINE_STORE
              value: {{ .Values.store.online | quote }}
            - name: FEATURE_OFFLINE_STORE
              value: {{ .Values.store.offline | quote }}
            - name: FEATURE_REDIS_URL
              value: {{ .Values.store.redis.url | quote }}
            {{- if .Values.store.postgres.enabled }}
            - name: FEATURE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "feature-platform.fullname" . }}-postgres
                  key: dsn
            {{- else }}
            - name: FEATURE_POSTGRES_DSN
              value: {{ .Values.store.postgres.dsn | quote }}
            {{- end }}
            - name: FEATURE_DATA_VERSION
              value: {{ .Values.store.dataVersion | quote }}
            - name: FEATURE_DRIFT_RETURN_DELTA_THRESHOLD
              value: {{ .Values.store.drift.returnDeltaThreshold | quote }}
            - name: FEATURE_DRIFT_VOLUME_DELTA_RATIO_THRESHOLD
              value: {{ .Values.store.drift.volumeDeltaRatioThreshold | quote }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
