{{- if .Values.store.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feature-platform.fullname" . }}-postgres
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "feature-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.store.postgres.username | quote }}
  password: {{ .Values.store.postgres.password | quote }}
  database: {{ .Values.store.postgres.database | quote }}
  dsn: {{ .Values.store.postgres.dsn | quote }}
{{- end }}
