tempo:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

persistence:
  enabled: false

service:
  type: ClusterIP

tempoQuery:
  enabled: false

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
